---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# TBhotspotclustersplos

<!-- badges: start -->

<!-- badges: end -->

The goal of TBhotspotclustersplos repository is to replicate the analysis of the manuscript:

*"Neighbourhood prevalence-to-notification ratios for adult bacteriologically-confirmed tuberculosis reveals hotspots of underdiagnosis in Blantyre, Malawi"*

Authors: McEwen Khundi^1,2^, James R Carpenter^1^, Elizabeth L Corbett^1,2^, Helena R A Feasey^1,2^, Rebecca Nzawa Soko^1,2^, Marriott Nliwasa^1,3^, Hussein Twabi^3^, Lingstone Chiume^1^, Rachael M Burke^1,2^, Katherine C Horton^2^, Peter J Dodd^4^, Ted Cohen^5^, Peter MacPherson^1,2^,^6^

1.  Malawi-Liverpool-Wellcome Trust Clinical Research Programme, Blantyre, Malawi,
2.  London School of Hygiene and Tropical Medicine, UK,
3.  Helse Nord TB Initiative, College of Medicine, University of Malawi,
4.  School of Health and Related Research, University of Sheffield, Sheffield, UK,
5.  Yale School of Public Health, New Haven, USA,
6.  Department of Clinical Sciences, Liverpool School of Tropical Medicine, UK

<br>

## Replicable code (Rscript folder description)

Description of the analysis scripts and source script of each output in the analysis

1.  Part1_exploratory_analysis_baseline_graphs_tables_2021-09-29.Rmd

    -   Script for producing table1, fig1 and fig2

2.  Part2_all_models_notif_car.R

    -   Script for producing notification icar models

3.  Part2_all_models_notif_rintc.R

    -   Script for producing notification random intercept models

4.  Part2_all_models_prev_car.R

    -   Script for producing prevalence icar models

5.  Part2_all_models_prev_rintc.R

    -   Script for producing prevalence random intercept models

6.  Part3_notification_models_loo_comparison_2021-09-29.R

    -   Script for model comparison of all notification models

7.  Part3_prevalence_models_loo_comparison_2021-09-29.R

    -   Script for model comparison of all prevalence models

8.  Part4_derive_posteriors_rintc_2021-09-29.Rmd

    -   Script for deriving posterior samples from the selected final models and also calculating the prevalence to notification ratios

9.  Part4_exploratory_analysis_posterior_rintc_2021-09-29.Rmd

    -   Exploratory analysis of the posterior samples generated in part 8 including graphs

    -   Source of fig3 and fig4

10. Part5_all_models_tables_appendix_notif_car.R

<!-- -->

    -   Source of table S4_Table_notif_models_car

1.  Part5_all_models_tables_appendix_notif_rintc.R

<!-- -->

    -   Souce of S2_Table_notif_models_rintc

1.  Part5_all_models_tables_appendix_prev_car.R

<!-- -->

    -   Source of S3_Table_prev_models_car

1.  Part5_all_models_tables_appendix_prev_rintc.R

<!-- -->

    -   Source of S1_Table_prev_models_rintc

<br>

## Data

### **`dat_scale.rds`**

Neighbourhood level variables

### **`dat_scale_ln.rds`**

Neighbourhood level variables in longitudinal format

## Sensitivity analysis

1.  All notified TB analysis

    -   https://github.com/mcewenkhundi/TBhotspotclustersallcasesplos

2.  Postistratified TB prevalence analysis

    -   <https://github.com/mcewenkhundi/TBhotspotclusterspoststratificationplos>
